Handle applications name starting with identically
micronaut-projects/micronaut-discovery-client pull request #439
Opened 2023-04-03 12:29 UTC by FrogDevelopper

Handle case when 2 applications have the same beginning for their name (#358)

2023-04-03 14:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-discovery-client?pullRequest=439) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-discovery-client?pullRequest=439) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: FrogDevelopper<br/>:x: Le Gall, Benoit<br/><hr/>**Le Gall, Benoit** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-discovery-client?pullRequest=439) it.</sub>

2023-04-10 14:27 UTC, alvarosanchez commented
@FrogDevelopper thank you very much for your contribution! 

Please note that the `master` branch is for the upcoming 4.x release, which will only be released with Micronaut 4. However, we can regard #358 as a bug, and hence it can be included in the next patch release of this module.

Can you please re-target this PR against the `3.3.x` branch?

2023-04-10 14:29 UTC, alvarosanchez requested changes
Please re-target this PR against the `3.3.x` branch

2023-04-11 13:15 UTC, FrogDevelopper commented
I think it will be better that I re-create branch from 3.3.x

2023-04-11 13:54 UTC, closed without merging