Fix resolveEnvironment method to get proper envName from fileName
micronaut-projects/micronaut-discovery-client pull request #532
Opened 2023-10-19 07:58 UTC by atrzcinski

With the existing code, the value of the `envName` variable will never be resolved correctly because the `resolveEnvironment` method will get the value of the `fileName` variable.

For example: if the name of the configuration file is `my-service-prod.yaml` (where **prod** is the name of the environment) and we provide `fileName` as a parameter (_value is my-service-prod_) instead of `finalName` (_value is my-service[alpha]_), then `resolveEnvironment` method will not be able to find environment.

The effect is that consul will overwrite the environment configuration with the standard configuration (e.g. `my-service.yaml`), i.e. the environment configuration will not be considered appropriate.

2023-11-10 18:55 UTC, jeremyg484 requested changes
This needs corresponding updates to the tests. 

It looks like https://github.com/micronaut-projects/micronaut-discovery-client/blob/master/discovery-client/src/test/groovy/io/micronaut/discovery/consul/ConsulMockConfigurationClientFilesSpec.groovy would be the place to start.

I'd like to see the test updated so that it fails without the change to ConsulConfigurationClient, but passes with it.

2023-11-16 14:17 UTC, atrzcinski commented
Sorry for delay with writing tests. I implemented second test with `v2` suffix. It shows, that different application-specific file name affects the final effect, so order of propertySources are different. With this fix, the priority of the propertySource parameter will be valid, so sorting will always be deterministic.

2023-11-16 22:35 UTC, jeremyg484 approved these changes

2024-01-03 10:01 UTC, atrzcinski commented
Hi, 

@jeremyg484 When do you plan to merge this change?

2024-01-12 12:29 UTC, jeremyg484 approved these changes

2024-01-12 12:31 UTC, merged