issues-652: see https://github.com/micronaut-projects/micronaut-disco…
micronaut-projects/micronaut-discovery-client pull request #664
Opened 2024-11-27 20:23 UTC by AndreyIvanovDev

…very-client/issues/652

1) add introspected
2) add setter for properySources
3) add default profile
100% working option

2024-11-27 20:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/micronaut-projects/micronaut-discovery-client?pullRequest=664) <br/>All committers have signed the CLA.

2025-01-02 09:56 UTC, sdelamo requested changes
You will need to sign the CLA

2025-01-02 09:58 UTC, sdelamo requested changes
It misses tests

2025-01-02 09:58 UTC, sdelamo commented on discovery-client/src/main/java/io/micronaut/discovery/spring/config/client/ConfigServerResponse.java
> +@Introspected
Classes annotated with `@Serdeable` are introspected. The `@Introspected` annotation is not need it.

2025-01-03 10:35 UTC, AndreyIvanovDev commented on discovery-client/src/main/java/io/micronaut/discovery/spring/config/client/ConfigServerResponse.java
> +@Introspected
Thank you, fix it.

2025-01-10 05:41 UTC, sdelamo commented
@AndreyIvanovDev can you sign the CLA?

2025-01-10 09:37 UTC, sdelamo commented
I created a PR which partially covers this PR https://github.com/micronaut-projects/micronaut-discovery-client/pull/684

2025-01-24 12:47 UTC, sdelamo approved these changes

2025-01-24 12:48 UTC, merged